config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get '/about',   to: 'static_pages#about'
  get '/help',    to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, heroku!"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
    @message = ""
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Retusn the title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Sample Application"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end
 

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Created by <%= link_to "Austin Aryain", 'http://austinaryain.com' %></small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "News", '#' %></li>
      </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sample Application", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Login", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js" type="text/javascript"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>About | Sample Application</h1>
    <p>
      You are on the static about page!
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="row">
  <div class="col-xs-12 col-md-2"></div>
  <div class="col-xs-12 col-md-8">
    <h1>Get in touch!</h1>
    <form class="form-horizontal" role="form" method="" action="">
    	<div class="form-group">
    		<label for="name" class="col-sm-2 control-label">Name</label>
    		<div class="col-sm-10">
    			<input type="text" class="form-control" id="name" name="name" placeholder="First & Last Name" value="">
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="email" class="col-sm-2 control-label">Email</label>
    		<div class="col-sm-10">
    			<input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" value="">
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="message" class="col-sm-2 control-label">Message</label>
    		<div class="col-sm-10">
    			<textarea class="form-control" rows="4" name="message"></textarea>
    		</div>
    	</div>
    	<div class="form-group">
    		<label for="human" class="col-sm-2 control-label">2 + 3 = ?</label>
    		<div class="col-sm-10">
    			<input type="text" class="form-control" id="human" name="human" placeholder="Your Answer">
    		</div>
    	</div>
    	<div class="form-group">
    		<div class="col-sm-10 col-sm-offset-2">
    			<input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
    		</div>
    	</div>
    	<div class="form-group">
    		<div class="col-sm-10 col-sm-offset-2">
    			<! Will be used to display an alert to the user>
    		</div>
    	</div>
    </form>
  </div>
  <div class="col-xs-12 col-md-2"></div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help | Sample Application</h1>
    <p>
      You are on the static help page!
    </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample Application</h1>
  <h2>This is the home page for the SAMPLE!</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails-logo.svg", alt: "Rails Logo"),
            'http://rubyonrails.org', class: "img-responsive" %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign Up</h1>
<p>Placeholder page for new user sign up form!</p>